### ISSUE TITLE
Support user-supplied `esbuild` binary

### ISSUE THREAD

**Issue by bee-plus** [lustre-labs/dev-tools#84]
Hi! It would be useful if Lustre's dev tools looked for `esbuild` in `$PATH` before trying to download it (or alternatively, if the user could specify a path to the binary).

Specifically, I'm trying to package a Lustre app using Nix and the build fails because networking is not allowed inside the sandbox.

Thank you!

**Comment by hayleigh-dot-dev** [comment]
It's now possible to supply either a local relative path or the special string `"system"` in your `gleam.toml` for both the tailwind and (now) bun binaries:

```toml
[tools.lustre.bin]
bun = "../some/other/place/bun"
tailwindcss = "system"
```
